name: Build and Push to AWS-ECS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build and tag the Docker image
        id: build-image
        run: |
          docker build -t nukeline .
          docker tag nukeline:latest 167261036202.dkr.ecr.ap-south-1.amazonaws.com/nukeline:latest
          docker push 167261036202.dkr.ecr.ap-south-1.amazonaws.com/nukeline:latest

      - name: Wait for ECR image
        id: wait-for-image
        run: |
          IMAGE_AVAILABLE=$(aws ecr describe-images \
            --repository-name nukeline \
            --image-ids imageTag=latest \
            --query 'imageDetails[0].imageTags[0]' \
            --output text)

          while [ "$IMAGE_AVAILABLE" != "latest" ]
          do
            echo "Waiting for latest image in ECR..."
            sleep 30
            IMAGE_AVAILABLE=$(aws ecr describe-images \
              --repository-name nukeline \
              --image-ids imageTag=latest \
              --query 'imageDetails[0].imageTags[0]' \
              --output text)
          done
      
      - name: Run ECS task
        run: |
          aws ecs run-task \
            --cluster nuke-cluster \
            --task-definition nuke-task \
